### ISSUE TITLE
Função sem docstring explicativa

### ISSUE THREAD

**Issue by RryanT** [Roxy222/roxy#1]
Seria bom que a função "Comprimenta" no arquivo main.py recebesse uma docstring explicando o uso dela

**Comment by fabiosilvdev** [comment]
preguissa

**Comment by RryanT** [comment]
Vou fzr um Pull request com uma sugestão de solução!

**Comment by RryanT** [comment]
Pull request enviado para analise geral. Vou fechar o Issue.
